import 'package:azure_stt_flutter/src/constants.dart';

class LanguageUtils {
  // This list is based on https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=stt
  static List<String> getSupportedLanguages() {
    return const [
      'af-ZA',
      'am-ET',
      'ar-AE',
      'ar-BH',
      'ar-DZ',
      'ar-EG',
      'ar-IL',
      'ar-IQ',
      'ar-JO',
      'ar-KW',
      'ar-LB',
      'ar-LY',
      'ar-MA',
      'ar-OM',
      'ar-PS',
      'ar-QA',
      'ar-SA',
      'ar-SY',
      'ar-TN',
      'ar-YE',
      'as-IN',
      'az-AZ',
      'bg-BG',
      'bn-IN',
      'bs-BA',
      'ca-ES',
      'cs-CZ',
      'cy-GB',
      'da-DK',
      'de-AT',
      'de-CH',
      'de-DE',
      'el-GR',
      'en-AU',
      'en-CA',
      'en-GB',
      'en-GH',
      'en-HK',
      'en-IE',
      'en-IN',
      'en-KE',
      'en-NG',
      'en-NZ',
      'en-PH',
      'en-SG',
      'en-TZ',
      'en-US',
      'en-ZA',
      'es-AR',
      'es-BO',
      'es-CL',
      'es-CO',
      'es-CR',
      'es-CU',
      'es-DO',
      'es-EC',
      'es-ES',
      'es-GQ',
      'es-GT',
      'es-HN',
      'es-MX',
      'es-NI',
      'es-PA',
      'es-PE',
      'es-PR',
      'es-PY',
      'es-SV',
      'es-US',
      'es-UY',
      'es-VE',
      'et-EE',
      'eu-ES',
      'fa-IR',
      'fi-FI',
      'fil-PH',
      'fr-BE',
      'fr-CA',
      'fr-CH',
      'fr-FR',
      'ga-IE',
      'gl-ES',
      'gu-IN',
      'he-IL',
      'hi-IN',
      'hr-HR',
      'hu-HU',
      'hy-AM',
      'id-ID',
      'is-IS',
      'it-CH',
      'it-IT',
      'ja-JP',
      'jv-ID',
      'ka-GE',
      'kk-KZ',
      'km-KH',
      'kn-IN',
      'ko-KR',
      'lo-LA',
      'lt-LT',
      'lv-LV',
      'mk-MK',
      'ml-IN',
      'mn-MN',
      'mr-IN',
      'ms-MY',
      'mt-MT',
      'my-MM',
      'nb-NO',
      'ne-NP',
      'nl-BE',
      'nl-NL',
      'or-IN',
      'pa-IN',
      'pl-PL',
      'ps-AF',
      'pt-BR',
      'pt-PT',
      'ro-RO',
      'ru-RU',
      'si-LK',
      'sk-SK',
      'sl-SI',
      'so-SO',
      'sq-AL',
      'sr-RS',
      'sv-SE',
      'sw-KE',
      'sw-TZ',
      'ta-IN',
      'te-IN',
      'th-TH',
      'tr-TR',
      'uk-UA',
      'ur-IN',
      'uz-UZ',
      'vi-VN',
      'wuu-CN',
      'yue-CN',
      'zh-CN',
      'zh-CN-shandong',
      'zh-CN-sichuan',
      'zh-HK',
      'zh-TW',
      'zu-ZA',
    ];
  }

  static String maximizeLocale(String languageCode) {
    // The Speech to text SDK only accepts languages in the format languageCode-regionCode
    if (languageCode.contains('-')) {
      return languageCode;
    }

    // If the user passes only the language code, we try to guess the most likely region
    const likelyRegions = {
      'af': 'af-ZA',
      'am': 'am-ET',
      'ar': 'ar-SA',
      'as': 'as-IN',
      'az': 'az-AZ',
      'bg': 'bg-BG',
      'bn': 'bn-IN',
      'bs': 'bs-BA',
      'ca': 'ca-ES',
      'cs': 'cs-CZ',
      'cy': 'cy-GB',
      'da': 'da-DK',
      'de': 'de-DE',
      'el': 'el-GR',
      'en': 'en-US',
      'es': 'es-ES',
      'et': 'et-EE',
      'eu': 'eu-ES',
      'fa': 'fa-IR',
      'fi': 'fi-FI',
      'fil': 'fil-PH',
      'fr': 'fr-FR',
      'ga': 'ga-IE',
      'gl': 'gl-ES',
      'gu': 'gu-IN',
      'he': 'he-IL',
      'hi': 'hi-IN',
      'hr': 'hr-HR',
      'hu': 'hu-HU',
      'hy': 'hy-AM',
      'id': 'id-ID',
      'is': 'is-IS',
      'it': 'it-IT',
      'ja': 'ja-JP',
      'jv': 'jv-ID',
      'ka': 'ka-GE',
      'kk': 'kk-KZ',
      'km': 'km-KH',
      'kn': 'kn-IN',
      'ko': 'ko-KR',
      'lo': 'lo-LA',
      'lt': 'lt-LT',
      'lv': 'lv-LV',
      'mk': 'mk-MK',
      'ml': 'ml-IN',
      'mn': 'mn-MN',
      'mr': 'mr-IN',
      'ms': 'ms-MY',
      'mt': 'mt-MT',
      'my': 'my-MM',
      'nb': 'nb-NO',
      'ne': 'ne-NP',
      'nl': 'nl-NL',
      'or': 'or-IN',
      'pa': 'pa-IN',
      'pl': 'pl-PL',
      'ps': 'ps-AF',
      'pt': 'pt-PT',
      'ro': 'ro-RO',
      'ru': 'ru-RU',
      'si': 'si-LK',
      'sk': 'sk-SK',
      'sl': 'sl-SI',
      'so': 'so-SO',
      'sq': 'sq-AL',
      'sr': 'sr-RS',
      'sv': 'sv-SE',
      'sw': 'sw-KE',
      'ta': 'ta-IN',
      'te': 'te-IN',
      'th': 'th-TH',
      'tr': 'tr-TR',
      'uk': 'uk-UA',
      'ur': 'ur-IN',
      'uz': 'uz-UZ',
      'vi': 'vi-VN',
      'wuu': 'wuu-CN',
      'yue': 'yue-CN',
      'zh': 'zh-CN',
      'zu': 'zu-ZA',
    };

    return likelyRegions[languageCode.toLowerCase()] ?? Constants.defaultLang;
  }
}
